# Generated by Django 3.0.7 on 2020-09-07 10:34

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название Юр. Лица')),
                ('side_one', models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default='1', max_length=1, verbose_name='Резидент РК')),
                ('ebin', models.CharField(blank=True, max_length=12, verbose_name='БИН РК')),
                ('etype', models.CharField(choices=[('1', 'ТОО'), ('2', 'ИП'), ('3', 'АО'), ('4', 'РАО'), ('5', 'ООО'), ('6', 'ОсО')], max_length=1, verbose_name='Тип организаций')),
                ('ebin2', models.CharField(blank=True, max_length=200, verbose_name='Иностранный Номер')),
            ],
        ),
        migrations.CreateModel(
            name='OwnCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название Юр. Лица')),
                ('ebin', models.CharField(blank=True, max_length=12, verbose_name='БИН РК')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('signer_one', models.CharField(choices=[('1', 'Первое лицо'), ('2', 'Сотрудник с Доверенностью'), ('3', 'Сотрудник без Доверенности'), ('4', 'Не сотрудник с Доверенностью')], default='1', max_length=1, verbose_name='Подписант 1')),
                ('signer_two', models.CharField(choices=[('1', 'Первое лицо'), ('2', 'Сотрудник с Доверенностью'), ('3', 'Сотрудник без Доверенности'), ('4', 'Не сотрудник с Доверенностью')], default='1', max_length=1, verbose_name='Подписант 2')),
                ('number', models.IntegerField(verbose_name='Номер Договора')),
                ('originity', models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default='1', max_length=1, verbose_name='Имеется Оригинал')),
                ('date_start', models.DateField(null=True, verbose_name='Дата Договора')),
                ('date_end', models.DateField(null=True, verbose_name='Окончание Договора')),
                ('upload_file', models.FileField(null=True, upload_to=blog.models.file_path)),
                ('side_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.OwnCompany', verbose_name='Сторона 1')),
                ('side_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Entity', verbose_name='Сторона 2')),
            ],
        ),
    ]
