# Generated by Django 3.1.3 on 2021-04-04 02:29

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название Юр. Лица')),
                ('side_one', models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default='1', max_length=1, verbose_name='Резидент РК')),
                ('ebin', models.CharField(blank=True, max_length=12, verbose_name='БИН РК')),
                ('etype', models.CharField(choices=[('1', 'ТОО'), ('2', 'ИП'), ('3', 'АО'), ('4', 'РАО'), ('5', 'ООО'), ('6', 'ОсО'), ('7', 'ОАО'), ('8', 'ЗАО'), ('9', 'ЧКПФ')], max_length=1, verbose_name='Тип организаций')),
                ('ebin2', models.CharField(blank=True, max_length=200, verbose_name='Иностранный Номер')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('ebin', 'ebin2')},
            },
        ),
        migrations.CreateModel(
            name='InMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='incoming', editable=False, max_length=20, verbose_name='Статус')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('in_number', models.IntegerField(verbose_name='Входящий Номер')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=blog.models.file_path)),
                ('topic', models.TextField(blank=True, max_length=20000, null=True, verbose_name='Тема')),
                ('state', models.CharField(default='editable', max_length=20, verbose_name='Состояние')),
                ('track_number', models.FileField(blank=True, null=True, upload_to=blog.models.file_path)),
            ],
        ),
        migrations.CreateModel(
            name='OwnCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название Юр. Лица')),
                ('ebin', models.CharField(blank=True, max_length=14, verbose_name='БИН РК')),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('number', models.IntegerField(verbose_name='Номер Допника')),
                ('date_start', models.DateField(null=True, verbose_name='Дата Допника')),
                ('date_end', models.DateField(null=True, verbose_name='Окончание Допника')),
                ('upload_file1', models.FileField(blank=True, null=True, upload_to=blog.models.file_path)),
                ('upload_file2', models.FileField(blank=True, null=True, upload_to=blog.models.file_path)),
                ('upload_file3', models.FileField(blank=True, null=True, upload_to=blog.models.file_path)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(default='', max_length=200, verbose_name='Фамилия')),
                ('email', models.CharField(default='', max_length=200, verbose_name='E-mail')),
                ('phone', models.CharField(default='', max_length=200, verbose_name='Номер Телефона')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OutMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='outcoming', editable=False, max_length=20, verbose_name='Статус')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('out_number', models.IntegerField(verbose_name='Исходящий Номер')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=blog.models.file_path)),
                ('topic', models.TextField(blank=True, max_length=20000, null=True, verbose_name='Тема')),
                ('state', models.CharField(default='editable', max_length=20, verbose_name='Состояние')),
                ('track', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Номер Трэка')),
                ('track_number', models.FileField(blank=True, null=True, upload_to=blog.models.file_path)),
                ('init', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.worker', verbose_name='Инициатор')),
                ('own_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.owncompany', verbose_name='Наши компаний')),
                ('response_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.inmail', verbose_name='Ответ на письмо')),
                ('side_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.entity', verbose_name='Кому')),
            ],
            options={
                'unique_together': {('out_number', 'own_company')},
            },
        ),
        migrations.AddField(
            model_name='inmail',
            name='init',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.worker', verbose_name='Инициатор'),
        ),
        migrations.AddField(
            model_name='inmail',
            name='own_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.owncompany', verbose_name='Наши компаний'),
        ),
        migrations.AddField(
            model_name='inmail',
            name='response_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.outmail', verbose_name='Ответ на письмо'),
        ),
        migrations.AddField(
            model_name='inmail',
            name='side_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.entity', verbose_name='От кого'),
        ),
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('signer_one', models.CharField(choices=[('1', 'Первое лицо'), ('2', 'Сотрудник с Доверенностью'), ('3', 'Сотрудник без Доверенности'), ('4', 'Не сотрудник с Доверенностью')], default='1', max_length=1, verbose_name='Подписант 1')),
                ('signer_two', models.CharField(choices=[('1', 'Первое лицо'), ('2', 'Сотрудник с Доверенностью'), ('3', 'Сотрудник без Доверенности'), ('4', 'Не сотрудник с Доверенностью')], default='1', max_length=1, verbose_name='Подписант 2')),
                ('signer_three', models.CharField(blank=True, choices=[('1', 'Первое лицо'), ('2', 'Сотрудник с Доверенностью'), ('3', 'Сотрудник без Доверенности'), ('4', 'Не сотрудник с Доверенностью')], default='1', max_length=1, verbose_name='Подписант 3')),
                ('number', models.CharField(blank=True, default='', max_length=100, verbose_name='Номер Договора')),
                ('originity', models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default='1', max_length=1, verbose_name='Имеется Оригинал')),
                ('renew', models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default='1', max_length=1, verbose_name='Авто Продление')),
                ('date_start', models.DateField(null=True, verbose_name='Дата Договора')),
                ('date_end', models.DateField(null=True, verbose_name='Окончание Договора')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=blog.models.file_path)),
                ('status', models.CharField(default='current', editable=False, max_length=20, verbose_name='Статус')),
                ('upload_file2', models.FileField(blank=True, null=True, upload_to=blog.models.file_path)),
                ('upload_file3', models.FileField(blank=True, null=True, upload_to=blog.models.file_path)),
                ('upload_file4', models.FileField(blank=True, null=True, upload_to=blog.models.file_path)),
                ('upload_file5', models.FileField(blank=True, null=True, upload_to=blog.models.file_path)),
                ('init', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.worker', verbose_name='Инициатор')),
                ('own_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.owncompany', verbose_name='Сторона 1')),
                ('side_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Side 3+', to='blog.entity', verbose_name='Сторона 3')),
                ('side_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Side 2+', to='blog.entity', verbose_name='Сторона 2')),
                ('subs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.sub', verbose_name='Допника')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='inmail',
            unique_together={('in_number', 'own_company')},
        ),
    ]
