# Generated by Django 3.0.7 on 2020-09-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='side_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Side 2+', to='blog.Entity', verbose_name='Сторона 2'),
        ),
    ]
