# Generated by Django 3.0.7 on 2020-09-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogovor',
            old_name='side_one',
            new_name='own_company',
        ),
    ]
