# Generated by Django 2.2.7 on 2021-10-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owncompany',
            name='adress',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='owncompany',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название Юр.  Лица'),
        ),
    ]
