# Generated by Django 3.0.7 on 2020-09-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200907_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('number', models.IntegerField(verbose_name='Номер Допника')),
                ('date_start', models.DateField(null=True, verbose_name='Дата Допника')),
                ('date_end', models.DateField(null=True, verbose_name='Окончание Допника')),
            ],
        ),
    ]
