# Generated by Django 3.0.7 on 2020-09-12 17:11

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200912_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_number', models.IntegerField(verbose_name='Исходящий Номер')),
                ('upload_file', models.FileField(null=True, upload_to=blog.models.file_path)),
                ('own_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.OwnCompany', verbose_name='Наши компаний')),
                ('side_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Entity', unique=True, verbose_name='Кому')),
            ],
        ),
        migrations.CreateModel(
            name='InMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_number', models.IntegerField(verbose_name='Входящий Номер')),
                ('upload_file', models.FileField(null=True, upload_to=blog.models.file_path)),
                ('own_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.OwnCompany', verbose_name='Наши компаний')),
                ('side_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Entity', unique=True, verbose_name='От кого')),
            ],
        ),
    ]
