# Generated by Django 3.0.7 on 2020-09-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogovor',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Sub', verbose_name='Допника'),
        ),
    ]
