# Generated by Django 3.0.7 on 2020-09-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_inmail_outmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmail',
            name='side_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Entity', verbose_name='От кого'),
        ),
        migrations.AlterField(
            model_name='outmail',
            name='side_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Entity', verbose_name='Кому'),
        ),
    ]
