# Generated by Django 3.0.7 on 2020-09-08 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_dogovor_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogovor',
            old_name='sub',
            new_name='subs',
        ),
        migrations.AddField(
            model_name='sub',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Dogovor', verbose_name='Договор'),
        ),
    ]
