# Generated by Django 3.0.7 on 2020-09-12 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200912_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmail',
            name='response_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.OutMail', verbose_name='Ответ на письмо'),
        ),
        migrations.AddField(
            model_name='outmail',
            name='response_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.InMail', verbose_name='Ответ на письмо'),
        ),
    ]
