# Generated by Django 3.0.7 on 2020-09-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200909_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='main',
        ),
    ]
