# Generated by Django 3.0.7 on 2020-09-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_sub_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogovor',
            name='status',
            field=models.CharField(default='В процессе', max_length=20, verbose_name='Статус'),
        ),
    ]
