# Generated by Django 3.0.7 on 2020-09-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200912_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmail',
            name='topic',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='outmail',
            name='topic',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Тема'),
        ),
    ]
