# Generated by Django 3.0.7 on 2020-09-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200912_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmail',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='outmail',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
