# Generated by Django 3.0.7 on 2020-09-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_dogovor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='status',
            field=models.CharField(default='current', editable=False, max_length=20, verbose_name='Статус'),
        ),
    ]
