# Generated by Django 3.0.7 on 2020-09-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200912_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outmail',
            old_name='in_number',
            new_name='out_number',
        ),
        migrations.AddField(
            model_name='inmail',
            name='status',
            field=models.CharField(default='incoming', editable=False, max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='outmail',
            name='status',
            field=models.CharField(default='outcoming', editable=False, max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='inmail',
            name='response_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.OutMail', verbose_name='Ответ на письмо'),
        ),
        migrations.AlterField(
            model_name='outmail',
            name='response_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.InMail', verbose_name='Ответ на письмо'),
        ),
    ]
