# Generated by Django 3.0.7 on 2020-09-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200909_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='subs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Sub', verbose_name='Допника'),
        ),
    ]
