# Generated by Django 3.0.7 on 2020-09-13 16:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200912_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmail',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.file_path),
        ),
        migrations.AlterField(
            model_name='outmail',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.file_path),
        ),
    ]
