# Generated by Django 3.0.7 on 2020-09-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200913_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='side_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Side 3+', to='blog.Entity', verbose_name='Сторона 3'),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='side_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Side 2+', to='blog.Entity', verbose_name='Сторона 2'),
        ),
    ]
