# Generated by Django 3.0.7 on 2020-09-13 19:34

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200914_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogovor',
            name='upload_file2',
            field=models.FileField(null=True, upload_to=blog.models.file_path),
        ),
        migrations.AddField(
            model_name='dogovor',
            name='upload_file3',
            field=models.FileField(null=True, upload_to=blog.models.file_path),
        ),
        migrations.AddField(
            model_name='dogovor',
            name='upload_file4',
            field=models.FileField(null=True, upload_to=blog.models.file_path),
        ),
        migrations.AddField(
            model_name='dogovor',
            name='upload_file5',
            field=models.FileField(null=True, upload_to=blog.models.file_path),
        ),
    ]
