# Generated by Django 3.0.7 on 2020-09-13 20:12

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200914_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.file_path),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='upload_file2',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.file_path),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='upload_file3',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.file_path),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='upload_file4',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.file_path),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='upload_file5',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.file_path),
        ),
    ]
