# Generated by Django 3.0.7 on 2020-09-14 19:02

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200914_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='upload_file1',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.file_path),
        ),
        migrations.AddField(
            model_name='sub',
            name='upload_file2',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.file_path),
        ),
        migrations.AddField(
            model_name='sub',
            name='upload_file3',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.file_path),
        ),
    ]
