# Generated by Django 3.0.7 on 2020-09-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200915_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogovor',
            name='renew',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default='1', max_length=1, verbose_name='Авто Продление'),
        ),
    ]
