# Generated by Django 3.0.7 on 2020-09-15 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_dogovor_renew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(default='', max_length=200, verbose_name='Фамилия')),
                ('email', models.CharField(default='', max_length=200, verbose_name='E-mail')),
                ('phone', models.CharField(default='', max_length=200, verbose_name='Номер Телефона')),
            ],
        ),
        migrations.AddField(
            model_name='dogovor',
            name='init',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Worker', verbose_name='Инициатор'),
        ),
    ]
