# Generated by Django 3.0.7 on 2020-09-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200915_2353'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inmail',
            unique_together={('in_number', 'own_company')},
        ),
        migrations.AlterUniqueTogether(
            name='outmail',
            unique_together={('out_number', 'own_company')},
        ),
    ]
