# Generated by Django 3.0.7 on 2020-09-15 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200916_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='init',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Worker', verbose_name='Инициатор'),
        ),
    ]
