# Generated by Django 3.0.7 on 2020-09-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200916_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmail',
            name='init',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Worker', verbose_name='Инициатор'),
        ),
        migrations.AddField(
            model_name='outmail',
            name='init',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Worker', verbose_name='Инициатор'),
        ),
    ]
