# Generated by Django 3.0.7 on 2020-09-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200917_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owncompany',
            options={},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['name']},
        ),
    ]
