# Generated by Django 2.2.7 on 2020-09-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200917_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name']},
        ),
    ]
