# Generated by Django 3.0.7 on 2020-09-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200917_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Номер Договора'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='etype',
            field=models.CharField(choices=[('1', 'ТОО'), ('2', 'ИП'), ('3', 'АО'), ('4', 'РАО'), ('5', 'ООО'), ('6', 'ОсО'), ('7', 'ОАО')], max_length=1, verbose_name='Тип организаций'),
        ),
    ]
