# Generated by Django 3.0.7 on 2020-09-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200927_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outmail',
            name='status',
            field=models.CharField(default='editable', max_length=20, verbose_name='Состояние'),
        ),
    ]
