# Generated by Django 3.0.7 on 2020-09-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200927_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='outmail',
            name='state',
            field=models.CharField(default='editable', max_length=20, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='outmail',
            name='status',
            field=models.CharField(default='outcoming', editable=False, max_length=20, verbose_name='Статус'),
        ),
    ]
