# Generated by Django 3.0.7 on 2020-09-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200927_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outmail',
            name='topic',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Тема'),
        ),
    ]
