# Generated by Django 3.0.7 on 2020-09-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200928_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmail',
            name='state',
            field=models.CharField(default='editable', max_length=20, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='inmail',
            name='topic',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Тема'),
        ),
    ]
