# Generated by Django 3.0.7 on 2020-09-29 17:07

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200928_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmail',
            name='track_number',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.file_path),
        ),
        migrations.AddField(
            model_name='outmail',
            name='track_number',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.file_path),
        ),
        migrations.AlterField(
            model_name='inmail',
            name='topic',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='outmail',
            name='topic',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='Тема'),
        ),
    ]
