# Generated by Django 3.0.7 on 2020-10-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20200929_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='etype',
            field=models.CharField(choices=[('1', 'ТОО'), ('2', 'ИП'), ('3', 'АО'), ('4', 'РАО'), ('5', 'ООО'), ('6', 'ОсО'), ('7', 'ОАО'), ('8', 'ЗАО'), ('9', 'ЧКПФ')], max_length=1, verbose_name='Тип организаций'),
        ),
        migrations.AlterField(
            model_name='owncompany',
            name='ebin',
            field=models.CharField(blank=True, max_length=14, verbose_name='БИН РК'),
        ),
    ]
