# Generated by Django 3.0.7 on 2020-10-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20201006_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='outmail',
            name='track',
            field=models.CharField(default='editable', max_length=20, verbose_name='Номер Трэка'),
        ),
    ]
