# Generated by Django 3.0.7 on 2020-10-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_outmail_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outmail',
            name='track',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Номер Трэка'),
        ),
    ]
