# Generated by Django 3.0.7 on 2020-10-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20201015_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmail',
            name='track',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Номер Трэка'),
        ),
    ]
