# Generated by Django 3.0.7 on 2020-10-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_inmail_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmail',
            name='track',
        ),
    ]
